# Generated by Django 4.2.1 on 2023-06-17 11:50

import DjangoWithOpenCVAlgorithms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='openCVimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('choice_field', models.TextField(max_length=100)),
                ('image', models.ImageField(default=None, null=True, upload_to=DjangoWithOpenCVAlgorithms.models.filePath)),
            ],
        ),
    ]
